version: '3'

services:
  db:
    image: mysql:8.0
    container_name: agricare_db
    restart: always
    environment:
      MYSQL_DATABASE: agricare_db
      MYSQL_USER: agricare_user
      MYSQL_PASSWORD: your_secure_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build: .
    container_name: agricare_web
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SECRET_KEY=your_secure_secret_key_here
      - DB_HOST=db
      - DB_NAME=agricare_db
      - DB_USER=agricare_user
      - DB_PASSWORD=your_secure_password
    command: >
      bash -c "python manage.py migrate --noinput &&
               python manage.py collectstatic --noinput &&
               gunicorn agricare.wsgi:application --bind 0.0.0.0:8000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: agricare_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
  static_volume:
  media_volume: 