@echo off
echo Starting AgriCare in production mode...
call venv\Scripts\activate
set DJANGO_SETTINGS_MODULE=agricare.production_settings
echo Creating logs directory if it doesn't exist...
if not exist logs mkdir logs
echo Installing Gunicorn if not already installed...
pip install gunicorn whitenoise
echo Collecting static files...
python manage.py collectstatic --noinput --settings=agricare.production_settings
echo Starting Gunicorn server...
gunicorn agricare.wsgi:application --bind 0.0.0.0:8000 